Scatter
biosciencedbc/jga-analysis pull request #3
Opened 2021-07-15 04:44 UTC by manabuishii

2021-07-16 01:12 UTC, hacchy1983 commented on per-sample/Workflows/per-sample.cwl
> +  # haplotypecaller interval=autosome-PAR, ploidy=2
interval_bed の入力を、
- autosome_PAR
- chrX_nonPAR
- chrY_nonPAR
の３種類にしていただくのはいかがでしょうか？

2021-07-16 01:13 UTC, hacchy1983 requested changes
入力パラメータのうち、interval_bed を４種類から３種類へ変更いただけたら幸いです。

2021-07-16 01:18 UTC, manabuishii commented on per-sample/Workflows/per-sample.cwl
> +  # haplotypecaller interval=autosome-PAR, ploidy=2
修正しました。
いかがでしょうか？

2021-07-16 01:20 UTC, hacchy1983 commented on per-sample/Workflows/per-sample.cwl
>    haplotypecaller_autosome_PAR_ploidy_2_interval_bed:
変数名を、`haplotypecaller_autosome_PAR_interval_bed` に変更するのはいかがでしょうか？（chrX_nonPAR との統一のため）

2021-07-16 01:23 UTC, hacchy1983 requested changes
`interval_bed` 関連変数の名前を統一いただけたら幸いです。

2021-07-16 01:30 UTC, hacchy1983 reviewed
コード良いと思います！テストして問題ないかご確認をお願いできますでしょうか？

2021-07-19 08:05 UTC, tafujino commented
outputs のうち haplotypecaller autosome-PAR, ploidy 2 に対応する VCF ファイルだけ短く `vcf_gz` で、他の例えば haplotypecaller chrX-nonPAR, ploidy 1 に関しては長い名前の `haplotypecaller_chrX_nonPAR_ploidy_1_vcf_gz` のようになっているのは意図的でしょうか？

2021-07-20 00:23 UTC, manabuishii commented
@tafujino 
レビューありがとうございます
autosome-PAR, ploidy 2 のoutputsの名前が短いのは、開発初期の名残で、意図的ではないため、修正しました。

2021-07-20 06:34 UTC, merged